version: '3.4'

services:
  api:
    container_name: "apic"
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8090:8080" 
      - "8091:8081" 